In [3]:
import numpy as np

### 11. Get the common items between a and b

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [4]:
np.intersect1d(a,b)

array([2, 4])

### 12. From array a remove all items present in array b

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [12]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

### 13. Get the positions where elements of a and b match

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [13]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. Get all items between 5 and 10 from a

In [14]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [19]:
# It is &, not 'and'.
#priority in python????
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

### 15. Convert the function maxx that works on two scalars, to work on two arrays.

In [1]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [5]:
pair_max = np.vectorize(maxx, otypes=[float])

In [6]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. Swap columns 1 and 2 in the array arr

In [7]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [9]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])